import type { AestheticName } from "@/contexts/AestheticThemeContext";

export const AESTHETIC_EXPRESSIONS: Record<AestheticName, { mood: string; cues: string[]; note: string }> = {
  "Soft Power": { mood: "Warm restraint with a polished edge.", cues: ["tailored silhouettes", "cream ceramics", "quiet gold hardware"], note: "For a composed expression that never needs to shout." },
  "Thrift Remix": { mood: "Layered, clever, and unmistakably personal.", cues: ["reworked denim", "mixed prints", "found-object detail"], note: "For original combinations and resourceful styling." },
  "Heritage Modern": { mood: "Contemporary form with material intelligence.", cues: ["carved wood", "sisal texture", "clean-lined foundations"], note: "Local making is referenced with care, never costume." },
  "Comfort Official": { mood: "Useful, relaxed, and quietly elevated.", cues: ["soft knits", "natural wood", "considered function"], note: "For ease that still feels intentional." },
  "Coastal Ease": { mood: "Airy calm with sunlit warmth.", cues: ["linen texture", "curved forms", "woven detail"], note: "For a lighter pace and a clear horizon." },
  "Savanna Atelier": { mood: "Architectural, grounded, and understated.", cues: ["stone surfaces", "sisal weave", "acacia-toned shadow"], note: "A quiet earth-led direction for home or wardrobe." },
  "Ink & Ivory": { mood: "Gallery contrast with deliberate negative space.", cues: ["framed art", "clean tailoring", "restrained brass"], note: "For a crisp edit with room to breathe." },
  "Orchid After Dark": { mood: "Romantic, artistic, and softly cinematic.", cues: ["plum accents", "velvet texture", "candle cream"], note: "For depth, intimacy, and a confident evening note." },
  "Tangerine Social": { mood: "Joyful energy with a measured focal point.", cues: ["bold accessories", "playful ceramics", "mint counterpoint"], note: "For celebrations, hosting, and expressive small moments." },
  "Moss & Marigold": { mood: "Optimistic, tactile, and a little unexpected.", cues: ["plants", "brushed cotton", "hand-painted colour"], note: "For warmth without defaulting to predictable neutrals." },
  "Cobalt Ritual": { mood: "Cool, crafted, and confidently geometric.", cues: ["cobalt depth", "polished metal", "strong lines"], note: "For crisp contrast that still feels human." },
  "Thermal Bloom": { mood: "Futuristic colour with editorial energy.", cues: ["infrared gradients", "ember accents", "electric violet"], note: "For music-night confidence and experimental expression." },
  "Soft Comfort": { mood: "Gentle, grounded, and made for exhaling.", cues: ["soft upholstery", "rounded edges", "warm light"], note: "For homes, outfits, and objects that make everyday life feel easier." },
  "Warm Minimal": { mood: "Simple forms with a little more feeling.", cues: ["quiet surfaces", "natural fibres", "one warm accent"], note: "For a calm direction that still feels lived in." },
  "Quiet Utility": { mood: "Useful, clear, and quietly strong.", cues: ["honest materials", "modular storage", "work-ready layers"], note: "For design that earns its place through everyday use." },
  "Earthbound Home": { mood: "Textured, natural, and close to the ground.", cues: ["clay tones", "woven rugs", "wood grain"], note: "For spaces and pieces that feel connected to place." },
  "Bright Play": { mood: "Colourful, curious, and full of small surprises.", cues: ["bright objects", "graphic shapes", "happy contrast"], note: "For playful rooms, gifts, accessories, and personal details." },
  "Street Archive": { mood: "A lived-in mix of movement and memory.", cues: ["layered denim", "found graphics", "old-new contrast"], note: "For fashion, objects, and spaces that carry a story." },
  "Studio Calm": { mood: "Focused, airy, and ready for making.", cues: ["clear worktops", "soft daylight", "precise storage"], note: "For creative rooms, workspaces, and tools that reduce friction." },
  "Pet Piece": { mood: "Thoughtful comfort for every member of the home.", cues: ["soft textures", "washable forms", "small custom details"], note: "For pets and people who want useful things with personality." },
  "Object Story": { mood: "A small piece can change the whole feeling.", cues: ["keepsake detail", "crafted texture", "meaningful display"], note: "For accessories, art, posters, rugs, wallets, and gifts with a point of view." },
  "Motion Detail": { mood: "Clean movement with a considered finish.", cues: ["fine lines", "polished surfaces", "road-ready utility"], note: "For cars, car care, travel pieces, and details that make motion feel personal." },
};
