import React from "react";
import { BadgeCheck, BellRing, ChevronRight, ClipboardCheck, EyeOff, Landmark, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { VibeLayout } from "@/components/VibeLayout";

const previewSections = [
  { Icon: ClipboardCheck, label: "Company review", title: "No company records are shown in this preview.", copy: "Verified company decisions stay inside the protected administrator workspace.", action: "Review queue" },
  { Icon: Landmark, label: "Commission controls", title: "Rates remain server-held.", copy: "SURA’s 20%–50% commission boundary and seller-settlement records are visible only to the platform administrator.", action: "Commission controls" },
  { Icon: BellRing, label: "Platform engagement", title: "Announcements are not published from preview.", copy: "Public contact routes, announcements, and offer-review decisions require authenticated administrator access.", action: "Engagement controls" },
];

export default function AdminDashboardPreview() {
  return <VibeLayout>
    <main className="container py-10 sm:py-14">
      <section className="overflow-hidden rounded-[2rem] border border-[#d8c6b1] bg-[#1d1b18] px-6 py-8 text-[#faf4eb] shadow-[0_24px_60px_rgba(31,23,15,0.16)] sm:px-10 sm:py-11">
        <div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-2xl"><p className="vb-kicker text-[#d7a261]">SURA / ADMINISTRATOR PREVIEW</p><h1 className="vb-serif mt-4 text-4xl leading-[0.95] sm:text-6xl">A quiet place to govern with care.</h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#d8cabc] sm:text-base">This preview shows the administrator workspace structure only. It contains no live users, companies, orders, payment records, or review data.</p></div><div className="flex items-center gap-3 rounded-2xl border border-[#5b5042] bg-[#27221d] px-4 py-3 text-sm"><EyeOff className="h-5 w-5 text-[#d7a261]" /><span><strong className="block text-[#faf4eb]">Privacy-safe preview</strong><span className="text-xs text-[#cbbca9]">Read-only, no live records</span></span></div></div>
        <div className="mt-9 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#554a3c] bg-[#27221d] p-4"><UsersRound className="h-4 w-4 text-[#d7a261]" /><p className="mt-5 text-2xl font-bold">0</p><p className="mt-1 text-xs text-[#d8cabc]">Private records revealed</p></div><div className="rounded-2xl border border-[#554a3c] bg-[#27221d] p-4"><BadgeCheck className="h-4 w-4 text-[#d7a261]" /><p className="mt-5 text-2xl font-bold">20–50%</p><p className="mt-1 text-xs text-[#d8cabc]">Commission governance range</p></div><div className="rounded-2xl border border-[#554a3c] bg-[#27221d] p-4"><ShieldCheck className="h-4 w-4 text-[#d7a261]" /><p className="mt-5 text-2xl font-bold">Server-held</p><p className="mt-1 text-xs text-[#d8cabc]">Review and payment boundaries</p></div></div>
      </section>
      <section className="mt-8 grid gap-6 lg:grid-cols-[15rem_1fr]"><aside className="rounded-[1.6rem] border border-[#ded1bf] bg-[#fbf8f2] p-3"><p className="px-3 pt-2 text-xs font-bold uppercase tracking-[0.12em] text-[#9d5b2d]">Workspace</p><div className="mt-3 space-y-1">{previewSections.map(({ Icon, label }) => <div key={label} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[#625342]"><Icon className="h-4 w-4 text-[#a66732]" />{label}</div>)}</div><div className="mt-4 border-t border-[#e5dbcf] px-3 pt-4 text-xs leading-5 text-[#756655]">Live administrator routes require a verified, registered account and server-enforced administrator role.</div></aside><div className="space-y-5">{previewSections.map(({ Icon, label, title, copy, action }) => <article key={label} className="rounded-[1.6rem] border border-[#ded1bf] bg-[#fbf8f2] p-6 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#efe4d4] text-[#a66732]"><Icon className="h-5 w-5" /></div><p className="vb-kicker text-[#9d5b2d]">{label}</p></div><h2 className="vb-serif mt-5 text-3xl text-[#2d2219]">{title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#756655]">{copy}</p></div><button disabled className="rounded-full border border-[#d4c2b0] px-4 py-2 text-xs font-bold text-[#8a7865] opacity-70">{action}</button></div></article>)}</div></section>
      <section className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-[1.6rem] border border-dashed border-[#d4bea3] bg-[#fffaf3] p-6"><div><p className="vb-kicker text-[#9d5b2d]">Secure next step</p><h2 className="vb-serif mt-2 text-3xl text-[#2d2219]">Open the protected workspace only after email verification.</h2></div><Link href="/join" className="vb-button vb-focus inline-flex items-center gap-2 rounded-full bg-[#1d1b18] px-5 py-3 text-sm font-bold text-[#fbf7ef]">Go to secure account access <ChevronRight className="h-4 w-4" /></Link></section>
    </main>
  </VibeLayout>;
}
