import { ArrowUpRight, Bookmark, Loader2, Share2, Sparkles } from "lucide-react";
import { useMemo } from "react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { VibeLayout, formatKes } from "@/components/VibeLayout";
import { VendorCard } from "@/components/VendorCard";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

type Selection = { buildId: number | null; vendorId: number | null };

export default function BuildBoard() {
  const [, setLocation] = useLocation();
  const { user, loading, isAuthenticated } = useAuth();
  const savedIds = trpc.board.savedVendorIds.useQuery(undefined, { enabled: isAuthenticated });
  const selections = trpc.board.selections.useQuery(undefined, { enabled: isAuthenticated });
  const vendors = trpc.vendors.list.useQuery(undefined, { enabled: isAuthenticated });
  const builds = trpc.builds.list.useQuery(undefined, { enabled: isAuthenticated });
  const share = trpc.shares.create.useMutation({ onSuccess: (data) => setLocation(`/share/${data.shareToken}`) });
  const selectedVendorIds = (savedIds.data ?? []) as number[];
  const selectedBuildIds = ((selections.data ?? []) as Selection[]).map((selection) => selection.buildId).filter((id): id is number => id !== null);
  const boardVendors = useMemo(() => (vendors.data ?? []).filter((vendor) => selectedVendorIds.includes(vendor.id)), [vendors.data, selectedVendorIds.join(",")]);
  const boardBuilds = useMemo(() => (builds.data ?? []).filter((build) => selectedBuildIds.includes(build.id)), [builds.data, selectedBuildIds.join(",")]);
  const totalItems = boardVendors.length + boardBuilds.length;
  const isLoading = savedIds.isLoading || selections.isLoading || vendors.isLoading || builds.isLoading;
  const hasDataError = savedIds.isError || selections.isError || vendors.isError || builds.isError;

  if (loading) return <VibeLayout><main className="container grid min-h-[60vh] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#a76531]" /></main></VibeLayout>;
  if (!isAuthenticated) return <VibeLayout><main className="container grid min-h-[66vh] place-items-center py-16"><section className="max-w-xl rounded-[2rem] border border-[#dccfbe] bg-[#fbf8f2] p-8 text-center shadow-[0_18px_45px_rgba(61,43,23,0.07)] sm:p-12"><Bookmark className="mx-auto h-9 w-9 text-[#ad6833]" /><span className="vb-kicker mt-6 block text-[#9f5d2d]">Your planning space</span><h1 className="vb-serif mt-4 text-4xl leading-[0.98] text-[#2a211a] sm:text-5xl">Keep the good directions close.</h1><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-[#756655]">Sign in to keep local sources and curated edits on a private SURA board. When it is ready, turn it into a clean public build link.</p><button onClick={() => startLogin()} className="vb-button vb-focus mt-7 inline-flex items-center gap-2 rounded-full bg-[#1e1b17] px-6 py-3.5 text-sm font-bold text-[#fbf7ef]">Sign in to your board <ArrowUpRight className="h-4 w-4" /></button></section></main></VibeLayout>;
  if (hasDataError) return <VibeLayout><main className="container grid min-h-[62vh] place-items-center py-14"><section className="max-w-lg rounded-[1.75rem] border border-[#dfb2a0] bg-[#fff3ed] p-8 text-center"><p className="vb-kicker text-[#9b4e36]">Your board is still yours</p><h1 className="vb-serif mt-3 text-3xl text-[#5f2c20]">We could not open it just now.</h1><p className="mt-3 text-sm leading-6 text-[#7b4637]">Nothing has been removed. Try loading the board again in a moment.</p><button onClick={() => { savedIds.refetch(); selections.refetch(); vendors.refetch(); builds.refetch(); }} className="vb-button vb-focus mt-6 rounded-full bg-[#5e2c20] px-5 py-3 text-sm font-bold text-white">Reload board</button></section></main></VibeLayout>;

  return <VibeLayout><main className="container pb-20 pt-10 sm:pt-14"><div className="flex flex-wrap items-end justify-between gap-6"><div><span className="vb-kicker text-[#9f5d2d]">Your personal SURA board</span><h1 className="vb-serif mt-4 text-5xl leading-[0.94] tracking-[-0.045em] text-[#251f1a] sm:text-6xl">Keep the edit in <em className="font-normal text-[#aa6834]">motion.</em></h1><p className="mt-4 max-w-xl text-base leading-7 text-[#746656]">A private planning space for the sources and directions you want to return to. Welcome back, {user?.name ?? "there"}.</p></div>{totalItems > 0 && <button disabled={share.isPending} onClick={() => share.mutate({ title: `${user?.name ?? "My"} SURA edit`, summary: "A considered local plan shaped with SURA.", buildIds: selectedBuildIds, vendorIds: selectedVendorIds })} className="vb-button vb-focus inline-flex items-center gap-2 rounded-full bg-[#1e1b17] px-6 py-3.5 text-sm font-bold text-[#fbf7ef] disabled:opacity-70">{share.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Share2 className="h-4 w-4" />}{share.isPending ? "Making your link" : "Share this board"}</button>}</div>
    {share.isError && <p className="mt-5 rounded-xl border border-[#e4b6a5] bg-[#fff2ec] px-4 py-3 text-sm text-[#843e2d]">We could not make the share link yet. Please try again.</p>}
    {isLoading ? <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-64 animate-pulse rounded-[1.5rem] bg-[#ded1bf]" />)}</div> : totalItems === 0 ? <section className="mt-10 rounded-[2rem] border border-dashed border-[#c7b6a2] bg-[#f7f1e8] p-10 text-center"><Sparkles className="mx-auto h-8 w-8 text-[#ad6833]" /><h2 className="vb-serif mt-4 text-3xl text-[#483728]">Your board is ready for a point of view.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#756655]">Save a local studio from the directory, or keep a build recommendation after you shape your brief.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/discover" className="vb-button vb-focus rounded-full bg-[#1e1b17] px-5 py-3 text-sm font-bold text-[#fbf7ef]">Find a studio</Link><Link href="/brief" className="vb-button vb-focus rounded-full border border-[#b98450] px-5 py-3 text-sm font-bold text-[#5f4127]">Build an edit</Link></div></section> : <div className="mt-10 space-y-12">{boardBuilds.length > 0 && <section><div className="flex items-end justify-between"><div><span className="vb-kicker text-[#9f5d2d]">Saved directions</span><h2 className="vb-serif mt-2 text-3xl text-[#2a211a]">Builds to keep shaping</h2></div><p className="text-sm text-[#766755]">{boardBuilds.length} saved</p></div><div className="mt-5 grid gap-5 lg:grid-cols-2">{boardBuilds.map((build) => <article key={build.id} className="overflow-hidden rounded-[1.6rem] border border-[#ddcfbd] bg-[#fbf8f2]"><div className="grid sm:grid-cols-[0.78fr_1.22fr]"><img src={build.heroImageUrl} alt="Saved demonstration build" className="h-48 w-full object-cover sm:h-full" /><div className="p-5"><span className="vb-kicker text-[#9f5d2d]">Demo build · from {formatKes(build.totalMinKes)}</span><h3 className="vb-serif mt-3 text-3xl leading-[0.95] text-[#33271e]">{build.title}</h3><p className="mt-3 text-sm leading-6 text-[#756655]">{build.headline}</p><Link href="/brief" className="vb-focus mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#9e5d2b]">Revisit direction <ArrowUpRight className="h-4 w-4" /></Link></div></div></article>)}</div></section>}{boardVendors.length > 0 && <section><div className="flex items-end justify-between"><div><span className="vb-kicker text-[#9f5d2d]">Saved sources</span><h2 className="vb-serif mt-2 text-3xl text-[#2a211a]">Studios in your mix</h2></div><p className="text-sm text-[#766755]">{boardVendors.length} saved</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{boardVendors.map((vendor) => <VendorCard key={vendor.id} vendor={vendor} />)}</div></section>}</div>}
  </main></VibeLayout>;
}
