import React, { useState } from "react";
import { CheckCircle2, CircleAlert, CreditCard, ShieldCheck } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { SuraEmptyState, SuraErrorState, SuraPageSkeleton, SuraProcessing } from "@/components/SuraStates";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { company_membership: "Company launch membership", vendor_feature: "Featured local source", build_consultation: "Private build consultation" };

export default function CheckoutPage() {
  const catalog = trpc.payments.catalog.useQuery();
  const orders = trpc.payments.mine.useQuery();
  const createOrder = trpc.payments.createOrder.useMutation({ onSuccess: () => void orders.refetch() });
  const [created, setCreated] = useState(false);

  return <DashboardLayout eyebrow="SURA / PAYMENTS" title="A payment flow with boundaries." description="Choose an SURA service. We create a protected payment-order record; gateway credentials and payment details are handled only after a live provider is connected.">
    <section className="rounded-[1.6rem] border border-[#d4bea3] bg-[#fffaf3] p-5 sm:p-7"><div className="flex gap-3"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-[#a66732]" /><div><h2 className="text-base font-bold text-[#3c2e22]">No sensitive payment credentials here.</h2><p className="mt-1 text-sm leading-6 text-[#756655]">This secure draft flow intentionally collects no card number, M-Pesa PIN, or account password. A provider must be connected and callback-verified before checkout can collect funds.</p></div></div></section>
    <section aria-label="M-Pesa availability" className="mt-4 rounded-[1.4rem] border border-[#e2cda9] bg-[#fff8e9] p-5"><div className="flex gap-3"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-[#9c5c27]" /><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-bold text-[#4a301d]">M-Pesa is not available for payment collection yet.</h2><span className="rounded-full bg-[#f0dfbd] px-2.5 py-1 text-[0.62rem] font-extrabold uppercase tracking-[0.1em] text-[#80501f]">Provider activation pending</span></div><p className="mt-2 text-sm leading-6 text-[#6f5844]">You can create a protected order reference today. SURA will not request an M-Pesa PIN, phone-payment approval, card detail, or money until approved Daraja onboarding and callback verification are complete.</p></div></div></section>
    {created && <div className="mt-6 rounded-2xl border border-[#c7ddc5] bg-[#f2f9f0] p-4 text-sm text-[#2f6334]"><CheckCircle2 className="mr-2 inline h-4 w-4" />Your protected payment order has been created. A payment gateway is still required to collect funds.</div>}
    <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="vb-kicker text-[var(--sura-accent)]">SURA services</p><h2 className="vb-serif mt-2 text-3xl">Choose a protected order type.</h2></div>{catalog.isError && <button onClick={() => catalog.refetch()} className="vb-button vb-focus rounded-full border border-[var(--sura-border)] px-4 py-2 text-xs font-bold">Retry services</button>}</div>{catalog.isLoading ? <div className="mt-5"><SuraPageSkeleton cards={3} dashboard /></div> : catalog.isError ? <div className="mt-5"><SuraErrorState title="Services need another moment." copy="Your private payment records remain available below. No payment detail was collected." onRetry={() => catalog.refetch()} /></div> : catalog.data && Object.keys(catalog.data).length > 0 ? <div className="mt-5 grid gap-5 lg:grid-cols-3">{Object.entries(catalog.data).map(([type, offer]) => <article key={type} className="flex flex-col rounded-[1.6rem] border border-[#ded1bf] bg-[#fbf8f2] p-6"><CreditCard className="h-5 w-5 text-[#a96b35]" /><p className="vb-kicker mt-6 text-[#9d5b2d]">SURA service</p><h3 className="vb-serif mt-2 text-3xl">{labels[type]}</h3><p className="mt-4 text-2xl font-bold text-[#2b2119]">KES {offer.amountKes.toLocaleString()}</p><p className="mt-3 flex-1 text-sm leading-6 text-[#756655]">{type === "company_membership" ? "Open and submit your company studio for review." : type === "vendor_feature" ? "Put a local source in a more visible editorial position." : "Receive a tailored private build direction."}</p><button disabled={createOrder.isPending} onClick={async () => { await createOrder.mutateAsync({ orderType: type as "company_membership" | "vendor_feature" | "build_consultation" }); setCreated(true); }} className="vb-button vb-focus mt-6 rounded-full bg-[#1d1b18] px-5 py-3 text-sm font-bold text-[#fbf7ef] disabled:opacity-60">Create payment order</button></article>)}</div> : <div className="mt-5"><SuraEmptyState eyebrow="SURA / PAYMENTS" title="No service orders are open right now." copy="No payment order can be created until a clearly defined SURA service is available. Your private records remain below." /></div>}</section>
    <section className="mt-10"><p className="vb-kicker text-[var(--sura-accent)]">Private order records</p><h2 className="vb-serif mt-2 text-3xl">Your payment records</h2>{orders.isLoading ? <div className="mt-5"><SuraProcessing eyebrow="SURA / PAYMENT RECORDS" title="Opening your private records." copy="Loading only the payment-order references associated with your account." /></div> : orders.isError ? <div className="mt-5"><SuraErrorState title="Your payment records need another moment." copy="No record was changed. You can still review available SURA services above." onRetry={() => orders.refetch()} /></div> : orders.data?.length === 0 ? <div className="mt-5"><SuraEmptyState eyebrow="SURA / PAYMENT RECORDS" title="No payment orders yet." copy="Create a protected service order above when you are ready. SURA will not collect a PIN or card credential here." /></div> : <div className="mt-5 overflow-hidden rounded-[1.5rem] border border-[#ded1bf] bg-[#fbf8f2]">{orders.data?.map((order) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e6dbcf] p-5 last:border-0"><div><p className="font-bold text-[#3b2d20]">{labels[order.orderType]}</p><p className="mt-1 text-xs text-[#7b6a58]">Reference: {order.reference}</p></div><div className="text-right"><p className="font-bold">KES {order.amountKes.toLocaleString()}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[0.08em] text-[#9d5b2d]">{order.status} · {order.provider}</p></div></div>)}</div>}</section>
  </DashboardLayout>;
}
