import { ArrowLeft, Check, Eye, ImagePlus, PackagePlus, ShieldCheck, Upload, X } from "lucide-react";
import { ChangeEvent, useState } from "react";
import { Link, useRoute } from "wouter";
import DashboardLayout from "@/components/DashboardLayout";
import { ProductGallery } from "@/components/ProductGallery";
import { SuraEmptyState, SuraErrorState, SuraPageSkeleton } from "@/components/SuraStates";
import { trpc } from "@/lib/trpc";

const emptyProduct = { name: "", category: "apparel" as const, description: "", priceKes: 0, sizeOptions: "", stockQuantity: 1, imageDataUrls: [] as string[] };

export default function CompanyCatalogPage() {
  const [, params] = useRoute("/company/:id/catalog");
  const companyId = Number(params?.id ?? 0);
  const membership = trpc.companies.membership.useQuery({ companyId }, { enabled: companyId > 0, retry: false });
  const ownerAccess = membership.data?.memberRole === "owner";
  const products = trpc.companies.products.useQuery({ companyId }, { enabled: ownerAccess, retry: false });
  const create = trpc.companies.createProduct.useMutation({ onSuccess: () => { products.refetch(); setProduct(emptyProduct); setImageError(""); } });
  const [product, setProduct] = useState(emptyProduct);
  const [imageError, setImageError] = useState("");

  const updateProduct = <K extends keyof typeof product>(key: K, value: (typeof product)[K]) => setProduct((current) => ({ ...current, [key]: value }));
  const handleImages = async (event: ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files ?? []);
    if (!files.length) return;
    const invalid = files.find((file) => !/^image\/(jpeg|png|webp)$/.test(file.type) || file.size > 5 * 1024 * 1024);
    if (invalid) {
      setImageError("Use JPEG, PNG, or WebP images below 5 MB each.");
      event.target.value = "";
      return;
    }
    if (files.length > 8) {
      setImageError("A product can have up to eight images.");
      event.target.value = "";
      return;
    }
    try {
      const imageDataUrls = await Promise.all(files.map(readImageAsDataUrl));
      updateProduct("imageDataUrls", imageDataUrls);
      setImageError("");
    } catch {
      setImageError("We could not read those images. Try selecting them again.");
    }
    event.target.value = "";
  };
  const removeImage = (index: number) => updateProduct("imageDataUrls", product.imageDataUrls.filter((_, imageIndex) => imageIndex !== index));

  if (membership.isLoading) return <DashboardLayout eyebrow="SURA / CATALOG" title="Opening your catalog." description="Checking secure company membership."><SuraPageSkeleton cards={2} dashboard /></DashboardLayout>;
  if (membership.isError || membership.data?.memberRole !== "owner") return <DashboardLayout eyebrow="SURA / CATALOG" title="Catalog access is owner-controlled." description="Only company owners can publish or adjust seller products, stock, and prices."><SuraEmptyState eyebrow="SURA / OWNER ACCESS" title="This catalog stays with its owner." copy="No catalog detail was shown to this account. Return to an accessible company studio to continue." action={<Link href="/company" className="vb-button vb-focus inline-flex rounded-full bg-[var(--sura-primary)] px-5 py-3 text-sm font-bold text-[var(--sura-paper)]">Back to company studio</Link>} /></DashboardLayout>;
  if (products.isError) return <DashboardLayout eyebrow="SURA / COMPANY CATALOG" title="Your catalog needs another moment." description="No stock or product information was changed."><SuraErrorState title="We could not open this product catalog." copy="Try again when you are ready. Product information remains protected inside the company studio." onRetry={() => products.refetch()} /><Link href={`/company/${companyId}`} className="vb-focus mt-5 inline-flex text-sm font-bold text-[var(--sura-accent)]">Back to company management</Link></DashboardLayout>;

  return <DashboardLayout eyebrow="SURA / COMPANY CATALOG" title="Publish the whole product story." description="Companies upload the images and details. Sura makes the listing visible only when the company is verified and the item is active."><Link href={`/company/${companyId}`} className="vb-focus inline-flex items-center gap-2 text-sm font-bold text-[#795634]"><ArrowLeft className="h-4 w-4" />Back to company management</Link><div className="mt-7 grid gap-6 xl:grid-cols-[0.95fr_1.05fr]">
    <section className="rounded-[1.6rem] border border-[var(--sura-border)] bg-[var(--sura-paper)] p-6 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[var(--sura-primary)] text-[var(--sura-accent)]"><PackagePlus className="h-5 w-5" /></span><div><p className="vb-kicker text-[var(--sura-accent)]">Company publishing studio</p><h2 className="vb-serif mt-1 text-3xl">Add a product</h2></div></div><p className="mt-4 text-sm leading-6 text-[#756655]">Lead with the strongest image, then add alternate angles, detail shots, or colourways. The first image becomes the primary card image.</p>
      <div className="mt-6 space-y-4"><label className="block"><span className="text-xs font-black uppercase tracking-[0.08em] text-[#725f4c]">Product name</span><input value={product.name} onChange={(event) => updateProduct("name", event.target.value)} maxLength={160} className="vb-focus mt-2 w-full rounded-xl border border-[var(--sura-border)] bg-white p-3 text-sm" placeholder="e.g. Handwoven weekend tote" /></label><label className="block"><span className="text-xs font-black uppercase tracking-[0.08em] text-[#725f4c]">Category</span><select value={product.category} onChange={(event) => updateProduct("category", event.target.value as typeof product.category)} className="vb-focus mt-2 w-full rounded-xl border border-[var(--sura-border)] bg-white p-3 text-sm"><option value="apparel">Apparel</option><option value="footwear">Footwear</option><option value="home">Home</option><option value="accessory">Accessory</option></select></label><label className="block"><span className="flex items-center justify-between text-xs font-black uppercase tracking-[0.08em] text-[#725f4c]"><span>Description</span><span className="font-normal normal-case tracking-normal text-[#9a8976]">{product.description.length}/3000</span></span><textarea value={product.description} onChange={(event) => updateProduct("description", event.target.value)} maxLength={3000} className="vb-focus mt-2 min-h-32 w-full rounded-xl border border-[var(--sura-border)] bg-white p-3 text-sm leading-6" placeholder="What is it made from? What makes it useful? Include fit, care, or fulfilment details a customer should know." /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block"><span className="text-xs font-black uppercase tracking-[0.08em] text-[#725f4c]">Price (KES)</span><input type="number" min="50" value={product.priceKes || ""} onChange={(event) => updateProduct("priceKes", Number(event.target.value) || 0)} className="vb-focus mt-2 w-full rounded-xl border border-[var(--sura-border)] bg-white p-3 text-sm" placeholder="2500" /></label><label className="block"><span className="text-xs font-black uppercase tracking-[0.08em] text-[#725f4c]">Stock available</span><input type="number" min="0" value={product.stockQuantity} onChange={(event) => updateProduct("stockQuantity", Math.max(0, Number(event.target.value) || 0))} className="vb-focus mt-2 w-full rounded-xl border border-[var(--sura-border)] bg-white p-3 text-sm" placeholder="1" /></label></div><label className="block"><span className="text-xs font-black uppercase tracking-[0.08em] text-[#725f4c]">Options or sizes</span><input value={product.sizeOptions} onChange={(event) => updateProduct("sizeOptions", event.target.value)} className="vb-focus mt-2 w-full rounded-xl border border-[var(--sura-border)] bg-white p-3 text-sm" placeholder="S, M, L or Natural, Black" /></label>
        <div className="rounded-2xl border border-dashed border-[var(--sura-border)] bg-[var(--sura-page)] p-4"><div className="flex items-center justify-between gap-3"><div><p className="flex items-center gap-2 text-sm font-bold"><ImagePlus className="h-4 w-4 text-[var(--sura-accent)]" />Product gallery</p><p className="mt-1 text-xs leading-5 text-[#756655]">Up to 8 JPEG, PNG, or WebP images. The first is the hero.</p></div><label className="vb-button vb-focus inline-flex shrink-0 cursor-pointer items-center gap-2 rounded-full bg-[var(--sura-primary)] px-3.5 py-2.5 text-xs font-bold text-[var(--sura-paper)]"><Upload className="h-3.5 w-3.5" />Choose images<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={handleImages} className="sr-only" /></label></div>{imageError && <p className="mt-3 text-xs font-semibold text-[#9a4936]">{imageError}</p>}{product.imageDataUrls.length > 0 && <div className="mt-4 grid grid-cols-4 gap-2">{product.imageDataUrls.map((image, index) => <div key={`${image.slice(0, 20)}-${index}`} className="group relative aspect-square overflow-hidden rounded-xl bg-[#e7ddd0]"><img src={image} alt={`Selected product image ${index + 1}`} className="h-full w-full object-cover" /><button onClick={() => removeImage(index)} className="vb-focus absolute right-1.5 top-1.5 grid h-6 w-6 place-items-center rounded-full bg-[#1b1e16]/80 text-white opacity-0 transition-opacity group-hover:opacity-100" aria-label={`Remove image ${index + 1}`}><X className="h-3 w-3" /></button>{index === 0 && <span className="absolute bottom-1.5 left-1.5 rounded bg-[#d7ff4d] px-1.5 py-1 text-[0.55rem] font-black text-[#1a220e]">Hero</span>}</div>)}</div>}</div>
      </div><button disabled={!product.name.trim() || product.description.trim().length < 12 || product.priceKes < 50 || create.isPending} onClick={() => create.mutate({ companyId, name: product.name, category: product.category, description: product.description, priceKes: product.priceKes, imageUrls: [], imageDataUrls: product.imageDataUrls, sizeOptions: product.sizeOptions.split(",").map((item) => item.trim()).filter(Boolean), stockQuantity: product.stockQuantity })} className="vb-button vb-focus mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full bg-[var(--sura-primary)] px-5 py-3.5 text-sm font-bold text-[var(--sura-paper)] disabled:cursor-wait disabled:opacity-60">{create.isPending ? "Uploading and publishing…" : "Publish to secure catalog"}</button>{create.isError && <p className="mt-3 text-xs font-semibold text-[#9a4936]">{create.error.message || "We could not publish this product. Check the details and try again."}</p>}</section>

    <div className="space-y-6"><section className="rounded-[1.6rem] border border-[var(--sura-border)] bg-[var(--sura-paper)] p-6 sm:p-7"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Eye className="h-5 w-5 text-[var(--sura-accent)]" /><div><p className="vb-kicker text-[var(--sura-accent)]">Customer preview</p><h2 className="vb-serif mt-1 text-3xl">This is how it lands.</h2></div></div><span className="rounded-full bg-[#eee0c7] px-2.5 py-1.5 text-[0.62rem] font-bold uppercase tracking-[0.08em] text-[#775024]">Draft preview</span></div><div className="mt-6 overflow-hidden rounded-2xl border border-[var(--sura-border)] bg-white"><ProductGallery images={product.imageDataUrls} name={product.name || "Your product"} compact /><div className="p-5"><p className="vb-kicker text-[var(--sura-accent)]">{product.category} · your company</p><h3 className="mt-2 text-2xl font-black tracking-[-0.04em] text-[#2c241d]">{product.name || "Product name"}</h3><p className="mt-2 line-clamp-4 text-sm leading-6 text-[#756655]">{product.description || "A clear product description will appear here for customers."}</p><div className="mt-4 flex items-end justify-between"><span className="text-2xl font-black text-[#211b16]">{product.priceKes ? `KES ${product.priceKes.toLocaleString()}` : "KES price"}</span><span className="rounded-full bg-[#eef5d8] px-2.5 py-1 text-[0.62rem] font-bold text-[#53652b]">Preview only</span></div></div></div><p className="mt-4 flex gap-2 text-xs leading-5 text-[#756655]"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--sura-accent)]" />Customers see the item after your company is verified and the product is active. Images are stored in managed media storage.</p></section><section className="rounded-[1.6rem] border border-[#d8e5a7] bg-[#f4f8e7] p-5"><p className="text-sm font-black text-[#3f501d]">Publishing checklist</p><div className="mt-3 space-y-2 text-xs leading-5 text-[#607237]"><p className="flex gap-2"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0" />Use a well-lit hero image and show useful alternate angles.</p><p className="flex gap-2"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0" />Describe materials, fit, care, stock, and any limits honestly.</p><p className="flex gap-2"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0" />Submit discounts separately; they stay pending until admin approval.</p></div></section></div>
  </div><section className="mt-7 rounded-[1.6rem] border border-[var(--sura-border)] bg-[var(--sura-paper)] p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="vb-kicker text-[var(--sura-accent)]">Private catalog</p><h2 className="vb-serif mt-2 text-3xl">Your published product records.</h2></div><span className="inline-flex items-center gap-2 text-xs text-[#756655]"><ShieldCheck className="h-4 w-4 text-[var(--sura-accent)]" />Owner only</span></div>{products.isLoading ? <SuraPageSkeleton cards={2} dashboard /> : products.data?.length === 0 ? <p className="mt-6 rounded-xl bg-[var(--sura-muted)] p-5 text-sm leading-6 text-[#756655]">No products yet. Your first listing will appear here with its gallery, stock, and visibility state.</p> : <div className="mt-5 grid gap-3 md:grid-cols-2">{products.data?.map((item) => <article key={item.id} className="flex gap-4 rounded-2xl border border-[var(--sura-border)] bg-white p-3"><div className="h-24 w-24 shrink-0 overflow-hidden rounded-xl"><ProductGallery images={Array.isArray(item.imageUrls) ? item.imageUrls : item.imageUrl ? [item.imageUrl] : []} name={item.name} compact /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="truncate text-sm font-black text-[#2d241c]">{item.name}</p><p className="mt-1 text-xs text-[#756655]">{item.category} · {item.stockQuantity} in stock</p></div><strong className="shrink-0 text-sm text-[#2c241d]">KES {item.priceKes.toLocaleString()}</strong></div><div className="mt-3 flex flex-wrap items-center gap-2 text-[0.62rem] font-bold uppercase tracking-[0.08em]"><span className="rounded-full bg-[#eef5d8] px-2 py-1 text-[#53652b]">{item.isActive ? "Active" : "Paused"}</span><span className="rounded-full bg-[#eee5d8] px-2 py-1 text-[#78644f]">{Array.isArray(item.imageUrls) ? item.imageUrls.length : item.imageUrl ? 1 : 0} images</span></div></div></article>)}</div>}</section></DashboardLayout>;
}

function readImageAsDataUrl(file: File) {
  return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
}
