import React, { useEffect, useState } from "react";
import { ArrowLeft, Gift, Mail, PackageCheck, Plus, ShieldCheck, Truck } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import DashboardLayout from "@/components/DashboardLayout";
import { SuraEmptyState, SuraErrorState, SuraPageSkeleton } from "@/components/SuraStates";
import { resolveDashboardDestination } from "@/lib/dashboardAccess";
import { trpc } from "@/lib/trpc";

export default function CompanyDetailPage() {
  const [, params] = useRoute("/company/:id");
  const [, setLocation] = useLocation();
  const companyId = Number(params?.id ?? 0);
  const [contact, setContact] = useState({ label: "Bookings", contactType: "email" as const, value: "", isPublic: true, sortOrder: 0 });
  const [offer, setOffer] = useState({ code: "", title: "", description: "", discountType: "percentage" as const, discountValue: 10 });
  const [delivery, setDelivery] = useState({ sameCityDeliveryKes: 450, nationalDeliveryKes: 950, providerLabel: "Company delivery estimate" });
  const membership = trpc.companies.membership.useQuery({ companyId }, { enabled: Number.isInteger(companyId) && companyId > 0, retry: false });
  const ownerAccess = membership.data?.memberRole === "owner";
  const contacts = trpc.companies.contacts.useQuery({ companyId }, { enabled: ownerAccess, retry: false });
  const offers = trpc.companies.offers.useQuery({ companyId }, { enabled: ownerAccess, retry: false });
  const deliverySettings = trpc.companies.deliverySettings.useQuery({ companyId }, { enabled: ownerAccess, retry: false });
  const orders = trpc.companies.orders.useQuery({ companyId }, { enabled: ownerAccess, retry: false });
  const replaceContacts = trpc.companies.replaceContacts.useMutation({ onSuccess: () => void contacts.refetch() });
  const createOffer = trpc.companies.createOffer.useMutation({ onSuccess: () => { void offers.refetch(); setOffer({ code: "", title: "", description: "", discountType: "percentage", discountValue: 10 }); } });
  const updateDelivery = trpc.companies.updateDeliverySettings.useMutation({ onSuccess: () => void deliverySettings.refetch() });

  useEffect(() => {
    if (membership.isError) setLocation(resolveDashboardDestination(`/company/${companyId}`, "user", false));
  }, [membership.isError, companyId, setLocation]);
  useEffect(() => {
    if (deliverySettings.data) setDelivery(deliverySettings.data);
  }, [deliverySettings.data]);

  if (membership.isLoading) {
    return <DashboardLayout eyebrow="SURA / COMPANY" title="Opening your company studio." description="Checking secure company membership before showing management details."><SuraPageSkeleton cards={2} dashboard /></DashboardLayout>;
  }
  if (membership.isError || !membership.data) {
    return <DashboardLayout eyebrow="SURA / COMPANY" title="Returning to your company studio." description="Company management requires an active owner, manager, or editor membership."><SuraErrorState title="This company studio is not available to this account." copy="No management detail was shown. We are returning you to your accessible company space." /></DashboardLayout>;
  }
  if (ownerAccess && contacts.isLoading && offers.isLoading && deliverySettings.isLoading && orders.isLoading) {
    return <DashboardLayout eyebrow="SURA / COMPANY MANAGEMENT" title="Opening your company controls." description="Loading only the owner-managed company details for this secure studio."><SuraPageSkeleton cards={3} dashboard /></DashboardLayout>;
  }

  return <DashboardLayout eyebrow="SURA / COMPANY MANAGEMENT" title="A studio with secure boundaries." description="Only active company members can open this management space. Owner controls are used for public contacts, offers, delivery estimates, and settlement records.">
    <Link href="/company" className="vb-focus inline-flex items-center gap-2 text-sm font-bold text-[#795634]"><ArrowLeft className="h-4 w-4" />Back to all company spaces</Link>
    <section className="mt-7 rounded-[1.6rem] border border-[#ded1bf] bg-[#fbf8f2] p-7">
      <div className="flex items-start justify-between gap-4"><div><p className="vb-kicker text-[#9d5b2d]">Secure company access</p><h2 className="vb-serif mt-3 text-4xl">Member role: {membership.data.memberRole}</h2><p className="mt-3 max-w-lg text-sm leading-6 text-[#756655]">Company contact details, offers, and fulfilment estimates stay private until an owner chooses to publish an active product through verified SURA channels.</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--sura-primary)] text-[var(--sura-accent)]"><ShieldCheck className="h-5 w-5" /></div></div>
    </section>
    {!ownerAccess ? <section className="mt-6 rounded-[1.5rem] border border-dashed border-[#d2bda9] bg-[#f8f1e6] p-6 text-sm leading-6 text-[#725c47]">You can view this secure studio, but owner-level access is required before public contacts, discount offers, delivery estimates, or settlement records can be changed or viewed.</section> : <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <section className="rounded-[1.5rem] border border-[#ded1bf] bg-[#fbf8f2] p-6">
        <Mail className="h-5 w-5 text-[var(--sura-accent)]" /><h2 className="vb-serif mt-4 text-3xl">Public contact route</h2><p className="mt-2 text-sm leading-6 text-[#756655]">Share only the channel a customer should use. This replaces current public company contacts.</p>
        <input value={contact.label} onChange={(event) => setContact({ ...contact, label: event.target.value })} className="vb-focus mt-5 w-full rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm" placeholder="Bookings" />
        <select value={contact.contactType} onChange={(event) => setContact({ ...contact, contactType: event.target.value as typeof contact.contactType })} className="vb-focus mt-3 w-full rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm"><option value="email">Email</option><option value="phone">Phone</option><option value="whatsapp">WhatsApp</option><option value="address">Address</option></select>
        <input value={contact.value} onChange={(event) => setContact({ ...contact, value: event.target.value })} className="vb-focus mt-3 w-full rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm" placeholder="hello@yourstudio.co.ke" />
        <button onClick={() => replaceContacts.mutate({ companyId, contacts: [contact] })} disabled={!contact.value || replaceContacts.isPending} className="vb-button vb-focus mt-4 rounded-full bg-[var(--sura-primary)] px-5 py-3 text-sm font-bold text-[var(--sura-paper)]">Save contact</button>
        <div className="mt-5 space-y-2">{contacts.isLoading ? <SuraPageSkeleton cards={1} dashboard /> : contacts.isError ? <SuraErrorState title="Contacts need another moment." copy="No contact change was made." onRetry={() => contacts.refetch()} /> : contacts.data?.length ? contacts.data.map((item) => <p key={item.id} className="rounded-xl border border-[#e5dbce] bg-white p-3 text-sm"><strong>{item.label}:</strong> {item.value}</p>) : <SuraEmptyState title="No public contact route yet." copy="Add the first customer-facing route above; it stays private until your company chooses to publish it." icon={<Mail className="h-6 w-6" />} />}</div>
      </section>
      <section className="rounded-[1.5rem] border border-[#ded1bf] bg-[#fbf8f2] p-6">
        <Gift className="h-5 w-5 text-[var(--sura-accent)]" /><h2 className="vb-serif mt-4 text-3xl">Discount offer</h2><p className="mt-2 text-sm leading-6 text-[#756655]">Offers start as pending and only become public after SURA review.</p>
        <input value={offer.code} onChange={(event) => setOffer({ ...offer, code: event.target.value.toUpperCase() })} className="vb-focus mt-5 w-full rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm" placeholder="WELCOME10" />
        <input value={offer.title} onChange={(event) => setOffer({ ...offer, title: event.target.value })} className="vb-focus mt-3 w-full rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm" placeholder="A warm first visit" />
        <textarea value={offer.description} onChange={(event) => setOffer({ ...offer, description: event.target.value })} className="vb-focus mt-3 min-h-20 w-full rounded-xl border border-[#ded1bf] bg-white p-3 text-sm" placeholder="Offer details" />
        <div className="mt-3 flex gap-3"><select value={offer.discountType} onChange={(event) => setOffer({ ...offer, discountType: event.target.value as typeof offer.discountType })} className="vb-focus flex-1 rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm"><option value="percentage">Percentage</option><option value="fixed_kes">KES amount</option></select><input type="number" min="1" value={offer.discountValue} onChange={(event) => setOffer({ ...offer, discountValue: Number(event.target.value) || 1 })} className="vb-focus w-28 rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm" /></div>
        <button onClick={() => createOffer.mutate({ companyId, ...offer })} disabled={!offer.code || !offer.title || createOffer.isPending} className="vb-button vb-focus mt-4 inline-flex items-center gap-2 rounded-full border border-[var(--sura-border)] px-5 py-3 text-sm font-bold text-[var(--sura-ink)]"><Plus className="h-4 w-4" />Submit offer</button>
        <div className="mt-5 space-y-2">{offers.isLoading ? <SuraPageSkeleton cards={1} dashboard /> : offers.isError ? <SuraErrorState title="Offers need another moment." copy="No offer change was made." onRetry={() => offers.refetch()} /> : offers.data?.length ? offers.data.map((item) => <p key={item.id} className="rounded-xl border border-[#e5dbce] bg-white p-3 text-sm"><strong>{item.code}</strong> · {item.title} <span className="text-xs text-[#796957]">({item.status})</span></p>) : <SuraEmptyState title="No discount offers yet." copy="Prepare an offer above; it will remain pending until SURA completes its review." icon={<Gift className="h-6 w-6" />} />}</div>
      </section>
      <section className="rounded-[1.5rem] border border-[#ded1bf] bg-[#fbf8f2] p-6">
        <Truck className="h-5 w-5 text-[var(--sura-accent)]" /><h2 className="vb-serif mt-4 text-3xl">Delivery estimate settings</h2><p className="mt-2 text-sm leading-6 text-[#756655]">Set transparent whole-KES estimates used in connected product quotes. This is not a courier booking, dispatch promise, or payment collection flow.</p>
        {deliverySettings.isLoading ? <div className="mt-5"><SuraPageSkeleton cards={1} dashboard /></div> : deliverySettings.isError ? <div className="mt-5"><SuraErrorState title="Delivery settings need another moment." copy="No estimate was changed." onRetry={() => deliverySettings.refetch()} /></div> : <><label className="mt-5 block text-xs font-bold uppercase tracking-[0.08em] text-[#756452]">Estimate label<input value={delivery.providerLabel} onChange={(event) => setDelivery({ ...delivery, providerLabel: event.target.value })} maxLength={100} className="vb-focus mt-2 w-full rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm normal-case tracking-normal" placeholder="Company delivery estimate" /></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-[0.08em] text-[#756452]">Same-city KES<input type="number" min="0" value={delivery.sameCityDeliveryKes} onChange={(event) => setDelivery({ ...delivery, sameCityDeliveryKes: Math.max(0, Number(event.target.value) || 0) })} className="vb-focus mt-2 w-full rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm normal-case tracking-normal" /></label><label className="text-xs font-bold uppercase tracking-[0.08em] text-[#756452]">National KES<input type="number" min="0" value={delivery.nationalDeliveryKes} onChange={(event) => setDelivery({ ...delivery, nationalDeliveryKes: Math.max(0, Number(event.target.value) || 0) })} className="vb-focus mt-2 w-full rounded-xl border border-[#ded1bf] bg-white px-3 py-3 text-sm normal-case tracking-normal" /></label></div><button onClick={() => updateDelivery.mutate({ companyId, ...delivery })} disabled={!delivery.providerLabel.trim() || updateDelivery.isPending} className="vb-button vb-focus mt-4 rounded-full bg-[var(--sura-primary)] px-5 py-3 text-sm font-bold text-[var(--sura-paper)]">{updateDelivery.isPending ? "Saving…" : "Save delivery estimates"}</button></>}
      </section>
      <section className="xl:col-span-2 rounded-[1.5rem] border border-[#ded1bf] bg-[#fbf8f2] p-6"><p className="vb-kicker text-[var(--sura-accent)]">Order settlement records</p><h2 className="vb-serif mt-3 text-3xl">Delivery stays separate from your merchandise settlement.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#756655]">The owner-configured delivery estimate is captured at quote time. SURA commission is bounded at 20%–50%; this owner-only view shows recorded seller settlement for each order without customer identity.</p>{orders.isLoading ? <SuraPageSkeleton cards={1} dashboard /> : orders.isError ? <div className="mt-5"><SuraErrorState title="Settlement records need another moment." copy="No settlement data was changed." onRetry={() => orders.refetch()} /></div> : orders.data?.length === 0 ? <SuraEmptyState title="No order settlement records yet." copy="When an order is requested, its separate delivery estimate and seller settlement will appear here." icon={<PackageCheck className="h-6 w-6" />} /> : <div className="mt-5 grid gap-4 lg:grid-cols-2">{orders.data?.map((order) => <article key={order.id} className="rounded-xl border border-[#e5dbce] bg-white p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-bold">{order.product?.name ?? `Product #${order.productId}`}</p><p className="mt-1 text-xs text-[#756655]">Order #{order.id} · {order.status}</p></div><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#9d5b2d]">{order.commissionRatePct}% platform rate</p></div><dl className="mt-4 grid grid-cols-2 gap-x-5 gap-y-3 text-xs leading-5"><div><dt className="text-[#756655]">Merchandise</dt><dd className="font-bold">KES {order.merchandiseSubtotalKes.toLocaleString()}</dd></div><div><dt className="text-[#756655]">Separate delivery</dt><dd className="font-bold">KES {order.deliveryKes.toLocaleString()}</dd></div><div><dt className="text-[#756655]">SURA commission</dt><dd className="font-bold">KES {order.commissionKes.toLocaleString()}</dd></div><div><dt className="text-[#756655]">Seller settlement</dt><dd className="font-bold">KES {order.sellerSettlementKes.toLocaleString()}</dd></div></dl></article>)}</div>}</section>
    </div>}
  </DashboardLayout>;
}
