import { ArrowLeft, ArrowUpRight, Bookmark, CheckCircle2, CircleAlert, Instagram, Loader2, MapPin, MessageCircle, Timer } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { InquiryPanel } from "@/components/InquiryPanel";
import { VibeLayout, formatKes, labelize } from "@/components/VibeLayout";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

export default function VendorProfile() {
  const [, params] = useRoute("/vendors/:slug");
  const [, setLocation] = useLocation();
  const slug = params?.slug ?? "";
  const { isAuthenticated } = useAuth();
  const vendor = trpc.vendors.bySlug.useQuery({ slug }, { enabled: Boolean(slug) });
  const savedVendorIds = trpc.board.savedVendorIds.useQuery(undefined, { enabled: isAuthenticated });
  const saveVendor = trpc.board.saveVendor.useMutation({ onSuccess: () => savedVendorIds.refetch() });

  if (vendor.isLoading) return <VibeLayout><main className="container grid min-h-[60vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#a76531]" /><p className="vb-serif mt-4 text-2xl text-[#403126]">Opening the profile…</p></div></main></VibeLayout>;
  if (vendor.isError || !vendor.data) return <VibeLayout><main className="container grid min-h-[60vh] place-items-center"><div className="max-w-md rounded-[1.5rem] border border-[#ddb09f] bg-[#fff3ed] p-8 text-center"><CircleAlert className="mx-auto h-6 w-6 text-[#a04932]" /><h1 className="vb-serif mt-3 text-3xl text-[#5e2b20]">That profile is not available.</h1><p className="mt-2 text-sm leading-6 text-[#7c4637]">Return to the directory to keep exploring local directions.</p><Link href="/discover" className="vb-button vb-focus mt-5 inline-flex rounded-full bg-[#592b20] px-5 py-2.5 text-sm font-bold text-white">Back to directory</Link></div></main></VibeLayout>;

  const profile = vendor.data;
  const isSaved = ((savedVendorIds.data ?? []) as number[]).includes(profile.id);
  const save = () => isAuthenticated ? saveVendor.mutate({ vendorId: profile.id, shouldSave: !isSaved }) : startLogin();

  return <VibeLayout><main>
    <div className="container pt-8"><button onClick={() => setLocation("/discover")} className="vb-focus inline-flex items-center gap-2 text-sm font-semibold text-[#665544] hover:text-[#a36530]"><ArrowLeft className="h-4 w-4" />Back to the directory</button></div>
    <section className="container grid gap-8 pb-16 pt-7 lg:grid-cols-[1.03fr_0.97fr] lg:gap-12 lg:pb-24"><div className="relative min-h-[27rem] overflow-hidden rounded-[2rem] bg-[#bd8d65] sm:min-h-[34rem]"><img src={profile.portfolio[0]} alt={`${profile.name} demonstration portfolio`} className="h-full w-full object-cover" /><div className="absolute inset-x-5 bottom-5 flex items-end justify-between gap-4 rounded-2xl border border-white/25 bg-[#1d1b18]/80 p-4 text-[#fff9f0] backdrop-blur-md"><div><p className="vb-kicker text-[#e1aa62]">Demonstration profile</p><p className="mt-1 text-sm text-[#e7ddd0]">Details shown are illustrative for this MVP.</p></div><span className="rounded-full border border-white/25 px-3 py-1.5 text-xs font-bold">{labelize(profile.type)}</span></div></div><div className="flex flex-col justify-center"><div className="flex flex-wrap items-center gap-3"><span className="vb-kicker text-[#9f5d2d]">{profile.city} · {profile.neighbourhood}</span><span className="rounded-full bg-[#ead8b8] px-3 py-1.5 text-[0.65rem] font-bold uppercase tracking-[0.09em] text-[#765024]">Indicative pricing</span></div><h1 className="vb-serif mt-5 text-5xl leading-[0.94] tracking-[-0.045em] text-[#251f1a] sm:text-6xl">{profile.name}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-[#706252]">{profile.description}</p><div className="mt-7 border-y border-[#d9ccba] py-5"><p className="vb-kicker text-[#9e5d2d]">Point of view</p><p className="vb-serif mt-3 text-2xl leading-[1.14] text-[#443427]">“{profile.pointOfView}”</p></div><div className="mt-7 flex flex-wrap gap-2">{profile.aestheticTags.map((tag) => <span key={tag} className="rounded-full border border-[#d9cbb9] bg-[#fbf8f2] px-3 py-2 text-xs font-semibold text-[#665646]">{tag}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><InquiryPanel vendorId={profile.id} contextName={profile.name} /><button onClick={save} disabled={saveVendor.isPending} className="vb-button vb-focus inline-flex items-center gap-2 rounded-full border border-[#cfbda9] bg-[#fbf8f2] px-5 py-3.5 text-sm font-semibold text-[#513e2c] hover:border-[#a97843] disabled:opacity-70">{isSaved ? <CheckCircle2 className="h-4 w-4 text-[#9d5f2e]" /> : <Bookmark className="h-4 w-4" />}{isSaved ? "Saved to board" : "Save this studio"}</button><a href={profile.socialUrl} target="_blank" rel="noreferrer" className="vb-focus inline-flex items-center gap-2 rounded-full border border-[#cfbda9] bg-[#fbf8f2] px-5 py-3.5 text-sm font-semibold text-[#513e2c] hover:border-[#a97843]"><Instagram className="h-4 w-4" />{profile.socialHandle}</a></div></div></section>
    <section className="border-y vb-rule bg-[#eee6da]"><div className="container grid gap-10 py-14 lg:grid-cols-[0.9fr_1.1fr]"><div><span className="vb-kicker text-[#9f5d2d]">Services & spend</span><h2 className="vb-serif mt-4 text-4xl leading-[0.98] tracking-[-0.04em] text-[#271f19]">A clear starting range.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[#736554]">Prices are indicative for the demonstration profile. Ask for a current quote before you commit.</p><div className="mt-6 flex items-center gap-2 text-sm font-semibold text-[#5c442e]"><MapPin className="h-4 w-4 text-[#ad6832]" />{profile.locationText}</div></div><div className="divide-y divide-[#d5c7b7] border-y border-[#d5c7b7]">{profile.services.map((service) => <div key={service.title} className="grid gap-3 py-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-bold text-[#33271d]">{service.title}</p><p className="mt-1 text-sm text-[#776957]">{service.category} · {service.leadTime}</p></div><strong className="text-sm text-[#352a20]">{formatKes(service.priceFromKes)}–{formatKes(service.priceToKes)}</strong></div>)}</div></div></section>
    <section className="container grid gap-6 py-16 sm:grid-cols-[1fr_0.9fr] sm:items-center sm:py-20"><div><span className="vb-kicker text-[#9f5d2d]">The next step is personal</span><h2 className="vb-serif mt-4 max-w-xl text-4xl leading-[0.98] tracking-[-0.04em] text-[#251f1a] sm:text-5xl">Bring the build context with you.</h2><p className="mt-4 max-w-lg text-base leading-7 text-[#716453]">Start with a short build brief to give the conversation a point of view, budget, and useful direction. The structured inquiry is stored with this studio and the context you share.</p></div><div className="rounded-[1.75rem] bg-[#1d1b18] p-6 text-[#f9f2e9] sm:p-8"><MessageCircle className="h-6 w-6 text-[#d69b58]" /><p className="vb-serif mt-7 text-3xl leading-[1.02]">“A good inquiry gives the maker something real to respond to.”</p><div className="mt-7 flex items-center justify-between border-t border-white/15 pt-4 text-xs text-[#cdbfae]"><span className="inline-flex items-center gap-2"><Timer className="h-3.5 w-3.5 text-[#d69b58]" />Stored with context</span><button onClick={() => setLocation("/brief")} className="vb-button vb-focus inline-flex items-center gap-2 font-bold text-[#f6c88b]">Build a plan <ArrowUpRight className="h-3.5 w-3.5" /></button></div></div></section>
  </main></VibeLayout>;
}
