import { Check, Palette, RotateCcw } from "lucide-react";
import { useState } from "react";
import { AESTHETIC_THEMES, type AestheticName, useAestheticTheme } from "@/contexts/AestheticThemeContext";

export function AestheticPicker({ compact = false }: { compact?: boolean }) {
  const { aesthetic, setAesthetic, resetAesthetic } = useAestheticTheme();
  const [open, setOpen] = useState(false);
  return <div className="relative"><button onClick={() => setOpen(!open)} className="vb-focus inline-flex items-center gap-2 rounded-full border border-[var(--sura-border)] bg-[var(--sura-paper)] px-3 py-2 text-xs font-bold text-[var(--sura-ink)] shadow-sm" aria-expanded={open}><Palette className="h-3.5 w-3.5 text-[var(--sura-accent)]" />{compact ? <span className="hidden xl:inline">{aesthetic}</span> : <span>{aesthetic}</span>}</button>{open && <div className="absolute right-0 top-[calc(100%+0.5rem)] z-50 w-72 rounded-2xl border border-[var(--sura-border)] bg-[var(--sura-paper)] p-3 shadow-[0_18px_45px_rgba(48,33,16,0.16)]"><div className="flex items-center justify-between px-2 pb-2"><p className="vb-kicker text-[var(--sura-accent)]">Your visual direction</p><button onClick={() => { resetAesthetic(); setOpen(false); }} className="vb-focus inline-flex items-center gap-1 text-xs font-bold text-[var(--sura-ink)]"><RotateCcw className="h-3.5 w-3.5" />Reset</button></div><div className="space-y-1">{(Object.entries(AESTHETIC_THEMES) as [AestheticName, (typeof AESTHETIC_THEMES)[AestheticName]][]).map(([name, palette]) => <button key={name} onClick={() => { setAesthetic(name); setOpen(false); }} className={`vb-focus flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${aesthetic === name ? "bg-[var(--sura-soft)] text-[var(--sura-ink)]" : "text-[#655646] hover:bg-[#f1e9dd]"}`}><span className="flex gap-1"><i className="h-3 w-3 rounded-full" style={{ backgroundColor: palette.primary }} /><i className="h-3 w-3 rounded-full" style={{ backgroundColor: palette.accent }} /><i className="h-3 w-3 rounded-full border border-black/10" style={{ backgroundColor: palette.soft }} /></span><span className="flex-1 font-semibold">{name}</span>{aesthetic === name && <Check className="h-4 w-4 text-[var(--sura-accent)]" />}</button>)}</div></div>}</div>;
}
