import { ArrowUpRight, Building2, CreditCard, FileText, LayoutDashboard, LogOut, Menu, Settings, ShieldCheck, Sparkles, X } from "lucide-react";
import { type ReactNode, useState } from "react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { useAestheticTheme } from "@/contexts/AestheticThemeContext";
import { startLogin } from "@/const";

type DashboardLayoutProps = { title: string; eyebrow: string; description: string; children: ReactNode };

const baseNav = [
  { href: "/account", label: "My profile", icon: Settings },
  { href: "/company", label: "Company studio", icon: Building2 },
  { href: "/checkout", label: "Payments", icon: CreditCard },
  { href: "/board", label: "Build board", icon: Sparkles },
];

export default function DashboardLayout({ title, eyebrow, description, children }: DashboardLayoutProps) {
  const { user, loading, logout } = useAuth();
  const { palette } = useAestheticTheme();
  const [location, setLocation] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const nav = user?.role === "admin" ? [...baseNav, { href: "/admin", label: "Admin review", icon: ShieldCheck }] : baseNav;

  if (loading) return <div style={{ backgroundColor: palette.page }} className="vb-paper grid min-h-screen place-items-center"><div style={{ backgroundColor: palette.soft }} className="h-12 w-12 animate-pulse rounded-2xl" /></div>;
  if (!user) return <main style={{ backgroundColor: palette.page }} className="vb-paper grid min-h-screen place-items-center p-5"><section style={{ borderColor: palette.border, backgroundColor: palette.paper }} className="w-full max-w-5xl overflow-hidden rounded-[2rem] border shadow-[0_28px_80px_rgba(47,33,17,0.12)] lg:grid lg:grid-cols-[0.88fr_1.12fr]"><div style={{ backgroundColor: palette.primary }} className="hidden min-h-[34rem] flex-col justify-between p-10 text-[#fbf5ec] lg:flex"><div><img src="/manus-storage/sura-packaging-mark_299d54bf.svg" alt="SURA" className="h-11 w-11 rounded-xl" /><p style={{ color: palette.accent }} className="vb-kicker mt-8">SURA / PRIVATE SPACE</p><h1 className="vb-serif mt-4 text-5xl leading-[0.96]">A place to keep the good direction moving.</h1></div><p className="max-w-sm text-sm leading-6 text-[#d8cabc]">Profiles, company studios, secure payment records, and your saved local build thinking—held with intention.</p></div><div className="flex min-h-[34rem] flex-col justify-center p-7 sm:p-12"><Link href="/" style={{ color: palette.accent }} className="vb-focus inline-flex items-center gap-2 text-sm font-bold"><ArrowUpRight className="h-4 w-4 rotate-[225deg]" />Back to SURA</Link><p style={{ color: palette.accent }} className="vb-kicker mt-12">Your SURA account</p><h2 style={{ color: palette.ink }} className="vb-serif mt-4 text-5xl leading-[0.95]">Sign in to make the plan yours.</h2><p className="mt-5 max-w-md text-base leading-7 text-[#756655]">We use secure OAuth sign-in. Your session is protected; payment information is never entered or stored on this page.</p><button onClick={() => startLogin()} style={{ backgroundColor: palette.primary, color: palette.paper }} className="vb-button vb-focus mt-9 inline-flex w-full items-center justify-center gap-2 rounded-full px-6 py-4 text-sm font-bold">Continue securely <ArrowUpRight className="h-4 w-4" /></button><p className="mt-5 text-center text-xs leading-5 text-[#8b7a67]">By continuing, you can review our <Link href="/terms" className="underline underline-offset-2">Terms</Link> and <Link href="/privacy" className="underline underline-offset-2">Privacy Policy</Link>.</p></div></section></main>;

  return <div style={{ backgroundColor: palette.page, color: palette.ink }} className="min-h-screen"><header style={{ borderColor: palette.border, backgroundColor: `${palette.paper}f5` }} className="sticky top-0 z-40 border-b backdrop-blur"><div className="container flex h-[4.7rem] items-center justify-between gap-4"><Link href="/" style={{ color: palette.ink }} className="vb-focus flex items-center gap-2.5"><img src="/manus-storage/sura-packaging-mark_299d54bf.svg" alt="" className="h-8 w-8 rounded-lg" /><span className="flex flex-col leading-none"><span className="text-[0.82rem] font-extrabold tracking-[0.16em]">SURA</span><span style={{ color: palette.accent }} className="mt-1 text-[0.48rem] font-bold tracking-[0.16em]">PRIVATE SPACE</span></span></Link><div className="flex items-center gap-3"><span className="hidden text-right text-xs leading-4 text-[#776957] sm:block"><strong style={{ color: palette.ink }} className="block">{user.name ?? "Your account"}</strong>{user.role === "admin" ? "Platform administrator" : "Member account"}</span><button onClick={() => setMobileOpen(!mobileOpen)} style={{ borderColor: palette.border, backgroundColor: palette.paper, color: palette.ink }} className="vb-focus grid h-10 w-10 place-items-center rounded-full border md:hidden" aria-label="Toggle dashboard navigation">{mobileOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button><button onClick={logout} style={{ borderColor: palette.border, backgroundColor: palette.paper, color: palette.ink }} className="vb-focus hidden items-center gap-2 rounded-full border px-4 py-2 text-xs font-bold md:inline-flex"><LogOut className="h-3.5 w-3.5" />Sign out</button></div></div></header>
    <div className="container grid gap-8 py-7 md:grid-cols-[15.5rem_1fr] md:py-10"><aside className={`${mobileOpen ? "block" : "hidden"} rounded-[1.5rem] border border-[#ded1bf] bg-[#fbf8f2] p-3 shadow-[0_10px_28px_rgba(52,37,20,0.06)] md:sticky md:top-28 md:block md:h-fit`}><nav className="space-y-1">{nav.map((item) => { const Icon = item.icon; const active = location === item.href; return <button key={item.href} onClick={() => { setLocation(item.href); setMobileOpen(false); }} className={`vb-focus flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold transition-colors ${active ? "bg-[#1e1b17] text-[#fbf7ef]" : "text-[#625342] hover:bg-[#efe6da]"}`}><Icon className="h-4 w-4" />{item.label}</button>; })}</nav><div className="mt-5 border-t border-[#e5dbcf] pt-4"><Link href="/terms" className="vb-focus flex items-center gap-2 px-3 py-2 text-xs font-semibold text-[#7b6a58]"><FileText className="h-3.5 w-3.5" />Legal & privacy</Link><button onClick={logout} className="vb-focus flex w-full items-center gap-2 px-3 py-2 text-xs font-bold text-[#8b3d2d] md:hidden"><LogOut className="h-3.5 w-3.5" />Sign out</button></div></aside><main><div className="border-b border-[#ded1bf] pb-7"><p className="vb-kicker text-[#9d5b2d]">{eyebrow}</p><h1 className="vb-serif mt-3 text-4xl leading-[0.96] text-[#271f19] sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#756655] sm:text-base">{description}</p></div><div className="pt-7">{children}</div></main></div></div>;
}
