import { ArrowUpRight, ChevronRight, Plus } from "lucide-react";
import { SuraImage } from "@/components/SuraImage";

const fallbackSignals = [
  { title: "Nairobi after five", label: "Field note", image: "/assets/sura-auth-street.jpg" },
  { title: "A room with a pulse", label: "Quiet launch", image: "/assets/sura-auth-interior.jpg" },
  { title: "Made for the weekend", label: "New in", image: "/assets/sura-auth-hero.jpg" },
  { title: "The considered edit", label: "Saved signal", image: "/assets/sura-auth-street.jpg" },
];

type SignalVendor = { id?: number; slug?: string; name?: string; portfolio?: string[]; neighbourhood?: string; type?: string };

export function SuraSignalRail({ vendors = [], onOpen }: { vendors?: SignalVendor[]; onOpen: (vendor?: SignalVendor) => void }) {
  const signals = vendors.length ? vendors.slice(0, 4).map((vendor, index) => { const portfolioImage = vendor.portfolio?.[0]; const image = portfolioImage && !portfolioImage.startsWith("/manus-storage/") ? portfolioImage : fallbackSignals[index].image; return { title: vendor.name || fallbackSignals[index].title, label: vendor.neighbourhood || fallbackSignals[index].label, image, vendor }; }) : fallbackSignals.map((signal) => ({ ...signal, vendor: undefined }));
  return <section aria-labelledby="sura-signal-heading" className="mt-5 overflow-hidden rounded-[1.45rem] border border-[#dfd5c7] bg-[#fffdf9] p-4 shadow-[0_8px_24px_rgba(49,34,18,0.04)] dark:border-white/[0.1] dark:bg-[#1a1d17] dark:shadow-none sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="vb-kicker text-[#a66231] dark:text-[#d7ff4d]">SURA / LIVE SIGNAL</p><h2 id="sura-signal-heading" className="mt-1 text-sm font-black text-[#31281f] dark:text-[#f4efe6]">What just found its way in.</h2></div><button onClick={() => onOpen()} className="vb-focus inline-flex items-center gap-1 text-xs font-bold text-[#a66231] dark:text-[#d7ff4d]">Open signal <ChevronRight className="h-3.5 w-3.5" /></button></div><div className="mt-4 flex gap-3 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden snap-x">{signals.map((signal, index) => <button key={`${signal.title}-${index}`} onClick={() => onOpen(signal.vendor)} className="vb-focus group relative min-w-[8.4rem] snap-start overflow-hidden rounded-2xl text-left sm:min-w-[10rem]"><SuraImage src={signal.image} fallbackSrc={fallbackSignals[index % fallbackSignals.length].image} alt="" className="aspect-[0.8] w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute inset-0 bg-gradient-to-t from-[#11130f]/85 via-[#11130f]/10 to-transparent" /><span className="absolute inset-x-3 bottom-3"><span className="block text-[0.58rem] font-black uppercase tracking-[0.12em] text-[#d7ff4d]">{signal.label}</span><span className="mt-1 block line-clamp-2 text-sm font-black leading-tight text-white">{signal.title}</span></span>{index === 0 && <span className="absolute right-2 top-2 grid h-6 w-6 place-items-center rounded-full bg-[#d7ff4d] text-[#19210d]"><ArrowUpRight className="h-3 w-3" /></span>}</button>)}<button onClick={() => onOpen()} className="vb-focus group grid min-w-[5.4rem] snap-start place-items-center rounded-2xl border border-dashed border-[#cfc2b2] bg-[#f4eee6] px-3 text-center dark:border-white/20 dark:bg-white/[0.05]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#1f1b17] text-[#f8f3eb] transition group-hover:bg-[#d7ff4d] group-hover:text-[#19210d]"><Plus className="h-4 w-4" /></span><span className="mt-2 text-[0.65rem] font-black uppercase tracking-[0.1em] text-[#725f4c] dark:text-[#d3d1c7]">Make a signal</span></button></div></section>;
}
